services:
  actual_server:
    image: docker.io/actualbudget/actual-server:latest-alpine
    volumes:
      - actual:/data
    networks:
      - traefik
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.actual.entrypoints=websecure"
      - "traefik.http.routers.actual.rule=Host(`budget.cyberiumshadow.xyz`)"
      - "traefik.http.routers.actual.tls=true"
      - "traefik.http.services.actual.loadbalancer.server.port=5006"
      - "traefik.docker.network=traefik"
      - "flame.type=application" # "app" works too
      - "flame.name=actual"
      - "flame.url=https://budget.cyberiumshadow.xyz"

volumes:
  actual:

networks:
  traefik:
    external: true
